apiVersion: apps/v1
kind: Deployment
metadata:
  name: roboshop-user-deployment
spec:
  template: 
    metadata:
      labels:
        app: web
    spec:
      containers: 
        - image: clahandevops/user:latest
          name: user-container
          ports: 
            - containerPort: 80
  replicas: 3
  selector: 
    matchLabels:
      app: web    